


####日志文件的位置

#eureka:
#  client:
#    service-url:
#      defaultZone: http://128.160.186.229:8761/eureka/
#  instance:
#    instance-id: zte-interface-service:8773
#    prefer-ip-address: true 






    #mysql:
    #  jdbc:
    #    driverClass: com.mysql.jdbc.Driver
    #      jdbcUrl: jdbc:mysql://128.196.233.250:3306/csrcmdb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    #      user: report
    #      password: 123456

#oracle:
#  jdbc:
#    driverClass: oracle.jdbc.OracleDriver
#    jdbcUrl: jdbc:oracle:thin:@128.160.96.243:1521:zxin
#    user: zxdb_kf
#    password: db10$ZTE
#  log:
#    jdbc:
#      driverClass: oracle.jdbc.OracleDriver
#      jdbcUrl: jdbc:oracle:thin:@128.160.96.243:1521:zxin
#      user: zxdb_kf
#      password: db10$ZTE
#spring:
#  datasource:
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@128.160.96.243:1521:zxin
#      username: zxdb_kf
#      password: db10$ZTE
#      type: com.alibaba.druid.pool.DruidDataSource

