server:
  port: 5051

spring:
  application:
    name: eurekaConfigClient
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1.com:8081/eureka/,http://eurekaserver2.com:8082/eureka/

