server:
  port: 8773

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/,http://localhost:8081/eureka/
  instance:
    instance-id: zte-interface-service:8773
    prefer-ip-address: true

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyyMMddHHmmss
    joda-date-time-format: yyyyMMddHHmmss
    default-property-inclusion: non_null
  sleuth:
    sampler:
      percentage: 0.01
    enable: true
  application:
    name: zte-interface-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///csrcmdb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
#  profiles: prod

####日志文件的位置
logging:
  config: classpath:logback-boot.xml

info:
  app.name: zte-interface-service
  build.artifactId: $project.artifactId$
  build.version: $project.version$

mybatis:
  type-aliases-package: com.zte.inface.cdxc.model
  mapper-locations: classpath:application/persist/mapper/*.xml


#zte:
#  inface:
#    resources:
#      locations: classpath*:application/spring/all.xml
#httpClient pool config
httpclient:
  pool:
    maxtotal: 500
    maxperpoute: 100
    retrycount: 3
    retryEnabled: true
    connecttimeout: 20000
    readtimeout: 30000
    requesttimeout: 20000